# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: cinnamon

description: >-
  Universal Blue based Cinnamon image built with BlueBuild.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - ublue-os/packages
    group-install:
      with-optional: true
      packages:
        - cinnamon-desktop
    install:
      packages:
        - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
        - b43-fwcutter
        - lightdm
        - lightdm-gtk
        - slick-greeter
        - distrobox
        - uupd
    remove:
      packages:
        - gnome-calculator
        - file-roller
        - simple-scan
        - thunderbird

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - install-starship.sh

  - type: brew
    brew-analytics: false

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          name: flathub
          title: Flathub (System)
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
        install:
          - com.github.PintaProject.Pinta
          - com.github.tchx84.Flatseal
          - com.ranfdev.DistroShelf
          - io.github.flattool.Ignition
          - io.github.flattool.Warehouse
          - io.github.kolunmi.Bazaar
          - io.gitlab.adhami3310.Impression
          - io.missioncenter.MissionCenter
          - it.mijorus.smile
          - org.gnome.Calculator
          - org.gnome.Connections
          - org.gnome.DejaDup
          - org.gnome.FileRoller
          - org.gnome.Firmware
          - org.gnome.Logs
          - org.gnome.SimpleScan
          - org.gnome.Weather
          - org.gnome.baobab
          - org.mozilla.Thunderbird
          - page.tesk.Refine

  - type: systemd
    system:
      enabled:
        - lightdm.service
        - uupd.timer
      disabled:
        - rpm-ostreed-automatic.timer

  - type: signing
